import { test, expect } from "@playwright/test";
test("register, login, create, copy invite, logout and return through authentication", async ({ page, context }) => {
  await context.grantPermissions(["clipboard-read", "clipboard-write"]);
  const email = `demo-${Date.now()}@example.com`;
  const password = "test password 123";
  await page.goto("/dashboard");
  await expect(page).toHaveURL(/\/auth\?next=/);
  await page.getByRole("button", { name: "Create an account", exact: true }).click();
  await page.getByLabel("Display name").fill("Thesis Host");
  await page.getByLabel("Email", { exact: true }).fill(email);
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Register", exact: true }).click();
  await expect(page).toHaveURL(/\/dashboard$/);
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await expect(page).toHaveURL(/\/auth/);
  await page.getByLabel("Email", { exact: true }).fill(email); await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page).toHaveURL(/\/dashboard$/);
  await page.getByLabel("Meeting title (optional)").fill("Supervisor demo");
  await page.getByRole("button", { name: "Create meeting", exact: true }).click();
  await expect(page).toHaveURL(/\/meeting\/[a-f0-9-]+$/);
  await expect(page.getByRole("heading", { name: "Supervisor demo" })).toBeVisible();
  await expect(page.getByText("Thesis Host (you) · Host", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Camera", exact: true })).toBeDisabled();
  const invite = page.url();
  await page.getByRole("button", { name: "Copy invite link" }).click();
  await expect(page.getByText("Invite link copied.")).toBeVisible();
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(invite);
  await page.getByRole("link", { name: "Leave meeting", exact: true }).click();
  await expect(page.getByRole("link", { name: "Supervisor demo" })).toBeVisible();
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await expect(page).toHaveURL(/\/auth/);
  await page.goto(invite);
  await expect(page).toHaveURL(/\/auth\?next=/);
  expect(new URL(page.url()).searchParams.get("next")).toBe(new URL(invite).pathname);
  await page.getByLabel("Email", { exact: true }).fill(email); await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page).toHaveURL(invite);
  await expect(page.getByRole("heading", { name: "Supervisor demo" })).toBeVisible();
  await page.reload(); await expect(page.getByRole("heading", { name: "Supervisor demo" })).toBeVisible();
  await page.goto("/meeting/524ad042-e10d-4edc-93c0-62d1f32ce54f");
  await expect(page.getByText("Meeting not found.", { exact: true })).toBeVisible();
  await page.goto("/meeting/invalid"); await expect(page.getByRole("heading", { name: "Invalid meeting link" })).toBeVisible();
});
