import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Provider from "../@libs/context/Provider";
import { NextFontWithVariable } from "next/dist/compiled/@next/font";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const fontWithMorePropsCreateFn = (
     fontDefinition: NextFontWithVariable,
     originalVariableName: string,
   ) => {
     return { ...fontDefinition, originalVariableName };
   };

   const poppinsFont = fontWithMorePropsCreateFn(poppins, "--font-poppins");

  return (
    <html lang="en">
      <body className="bg-[#FBF9F5] designed_scrollbar">
        <Provider nextFont={[poppinsFont]}>{children}</Provider>
      </body>
    </html>
  );
}
