import { FEATURES, COORDINATES, validateConfig, type Config } from "./config.ts";
import { labelMap, normalizationState } from "./preprocess.ts";
import type { Vocabulary } from "../../src/@modules/research/types";
export function inferenceContract(config: Config, vocabulary: Vocabulary, status: "blocked" | "real-selected" | "synthetic-smoke", checksums: { vocabulary: string; split: string | null }) {
  return { contractVersion: 1, status, deployable: status === "real-selected", modelVersion: config.modelVersion, vocabularyVersion: vocabulary.version, checksums, labels: labelMap(vocabulary), input: { dtype: "float32", shape: [null, config.sequenceLength, FEATURES], sequenceLength: config.sequenceLength, featuresPerFrame: FEATURES, layout: { left: "0..62: x0,y0,z0,...,x20,y20,z20", right: "63..125: x0,y0,z0,...,x20,y20,z20", leftPresent: COORDINATES, rightPresent: COORDINATES + 1 } }, preprocessing: config, normalizationState: normalizationState(), geometric: { origin: "mean wrist xyz of reliably assigned hands in first valid frame", scale: "maximum absolute coordinate relative to this shared origin across every assigned point in the complete clip", depthLimit: "MediaPipe z is wrist-relative per hand, not calibrated inter-hand depth" }, missing: "zero coordinates plus per-hand 0 mask; all-zero rows are masked by the RNN", resampling: "inclusive linspace(0,durationMs,T), linear between adjacent valid observations only; gaps beyond configured limit and outside observed range are zero/masked; duplicate or unordered timestamps rejected", handedness: "Day-4 fixed physical slots: raw Right -> left, raw Left -> right for unmirrored pixels; confidence >=0.8; unassigned observations are not imputed", mirroring: "no coordinate flips; CSS preview only", output: { shape: [null, labelMap(vocabulary).length], activation: "softmax", interpretation: "uncalibrated relative class probabilities, not proof of correctness; no meeting acceptance threshold selected" }, unsupported: ["unreviewed labels", "continuous sentences", "automatic sign boundaries", "live meeting temporal inference", "unseen vocabulary", "mirrored input pixels", "uncertain handedness imputation"] };
}
export function validateContract(value: ReturnType<typeof inferenceContract>) {
  validateConfig(value.preprocessing);
  if (!["blocked", "real-selected", "synthetic-smoke"].includes(value.status) || value.modelVersion !== value.preprocessing.modelVersion || !value.vocabularyVersion || value.input.dtype !== "float32" || value.input.shape.length !== 3 || value.input.shape[0] !== null || value.input.layout.leftPresent !== COORDINATES || value.input.layout.rightPresent !== COORDINATES + 1 || value.output.activation !== "softmax" || value.output.shape.length !== 2 || value.output.shape[0] !== null || value.labels.some(label => !label.id || !label.bangla)) throw new Error("Inconsistent inference contract metadata");
  if (value.contractVersion !== 1 || value.input.featuresPerFrame !== FEATURES || value.input.shape[2] !== FEATURES || value.input.sequenceLength !== value.preprocessing.sequenceLength || value.input.shape[1] !== value.input.sequenceLength || value.labels.some((label, index) => label.index !== index) || new Set(value.labels.map(label => label.id)).size !== value.labels.length || value.output.shape[1] !== value.labels.length || value.deployable !== (value.status === "real-selected") || (value.deployable && (value.labels.length < 2 || !value.checksums.split))) throw new Error("Inconsistent inference contract");
}
